import type { Metadata } from 'next'
import '@/styles/globals.css'
import localFont from 'next/font/local'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const nun = localFont({
  src: '../../../public/fonts/nunito.ttf',
  weight: '400',
  variable: '--font-comfort',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`antialiased light`}>
      <body
        className={`w-screen bg-neutral-200 overflow-x-hidden ${nun.className}`}
      >
        <div className="w-full h-full">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
