import type { Metadata } from 'next'
import '@/styles/globals.css'
import localFont from 'next/font/local'
import React from 'react'
import { ClerkProvider } from '@clerk/nextjs'
import { Toaster } from '@/components/ui/toaster'
import { ConfettiProvider } from '@/providers/ConfettiProvider'

const nun = localFont({
  src: '../../public/fonts/nunito.ttf',
  weight: '400',
  variable: '--font-comfort',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en" className={`antialiased light`}>
        <body
          className={`w-screen bg-neutral-200 overflow-x-hidden ${nun.className}`}
        >
          <div className="w-full h-full">
            <ConfettiProvider />
            {children}
            <Toaster />
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}
